spring.application.name=data-accessor
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${PORT:8080}
springdoc.swagger-ui.enabled=true


management.endpoints.web.exposure.include=health,info,metrics,env,beans

logging.config=classpath:log4j2.xml
logging.level.org.springframework.security=INFO
logging.level.org.springdoc=INFO

springdoc.swagger-ui.operations-sorter=alpha