management.endpoint.env.show-values=always
logging.config=classpath:log4j2.xml
spring.datasource.url=jdbc:postgresql://localhost:5432/data_accessor_dev
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=500

# JWT Configuration
jwt.secret=VEhpc0lzQTI1NkJpdFNlY3JldEtleUZvckhNQUNTSEEyNTZEZXZPbmx5ISE=
jwt.expiration=86400000