spring.application.name=data-accessor
spring.profiles.active=dev
springdoc.swagger-ui.enabled=true


management.endpoints.web.exposure.include=health,info,metrics,env,beans

logging.config=classpath:log4j2.xml
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
logging.level.org.springframework.security=DEBUG
logging.level.org.springdoc=DEBUG

springdoc.swagger-ui.operations-sorter=alpha